no-permission: "<red>Commande inconnue."
error: "<dark_red>⚠ <reset><red>Error pendant l'exécution de cette commande"

below:
  worlds-whitelist:
    - "SuperiorWorld"
    - "SuperiorWorld_nether"
  enable: true
  permission: "rivrsessentials.below"
  success: "<dark_green><bold>✔ <reset><green>Vous avez été téléporté à la hauteur minimum."

transfert:
  enable: true
  permission: "trolliutils.transfert"
  success: "<dark_green><bold>✔ <reset><green>Vous avez bien transferé les données."
  success-target: "<dark_green><bold>✔ <reset><green>Vous avez été transféré de toutes vos données."

leaderboard-rewards:
  enable: true
  permission: "trolliutils.leaderboard-rewards"
  success: "<dark_green><bold>✔ <reset><green>Vous avez bien reçus les données récompenses de classement. <dark_gray>(%leaderboard_type% #%leaderboard_rank%)"
  rewards-commands:
    box:
      1:
        commands:
          - ""
          - ""
      2:
        commands:
          - ""
          - ""
      3:
        commands:
          - ""
          - ""
      4:
        commands:
          - ""
          - ""
      5:
        commands:
          - ""
          - ""
      6:
        commands:
          - ""
          - ""
      7:
        commands:
          - ""
          - ""
      8:
        commands:
          - ""
          - ""
      9:
        commands:
          - ""
          - ""
      10:
        commands:
          - ""
          - ""
    caps:
      1:
        commands:
          - ""
          - ""
      2:
        commands:
          - ""
          - ""
      3:
        commands:
          - ""
          - ""
      4:
        commands:
          - ""
          - ""
      5:
        commands:
          - ""
          - ""
      6:
        commands:
          - ""
          - ""
      7:
        commands:
          - ""
          - ""
      8:
        commands:
          - ""
          - ""
      9:
        commands:
          - ""
          - ""
      10:
        commands:
          - ""
          - ""
