name: TrolliUtils
version: '1.0.0'
main: fr.jesuistrolls.TrolliUtils
api-version: '1.20'
depend:
  - PlaceholderAPI
commands:
  below:
    usage: /below
  transfert:
    usage: /transfert <old_account> <new_account>
  leaderboardrewards:
    usage: /leaderboardrewards <leaderboard_type> <leaderboard_rank> <player_name>
authors: [ JeSuisTrolls ]
